FROM maven:3.9-eclipse-temurin-17 AS build

WORKDIR /app

COPY settings.xml /usr/share/maven/ref/settings.xml

COPY pom.xml .
RUN mvn -s /usr/share/maven/ref/settings.xml dependency:go-offline

COPY src ./src
RUN mvn -s /usr/share/maven/ref/settings.xml package -DskipTests

FROM eclipse-temurin:17-jre

WORKDIR /app

COPY --from=build /app/target/*.jar app.jar

EXPOSE 8000

ENV JAVA_OPTS="-Xmx1g -Xms512m -XX:+UseG1GC"

ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar app.jar"]
